version: '3'
services:
  food.api:
    image: node:20-alpine3.18
    ports:
      - 3000:3000
      - 9779:9779
    working_dir: /app
    environment:
      - NODE_ENV=development
      - TZ=America/Sao_Paulo
      - DB_API_MONGO=mongodb://team75:FIAP%23Team75@food.db:27017
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - food-network
    depends_on:
      - food.db
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run prebuild
        npm run start:debug

  food.db:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=team75
      - MONGO_INITDB_ROOT_PASSWORD=FIAP#Team75
    ports:
      - "27017:27017"
    volumes:
      - .database:/data/db
    networks: 
      - food-network

networks:
  food-network:
    driver: bridge
